const tkContent = [
    {
        name:'Faya',
        bp:'Strike / Dark',
        infos:'Vitae soli penetrali conscii susurrasset Marcio aurem referente postridie nullo disceret secreto paterfamilias acciderat secreto secreto in susurrasset paterfamilias imperator etiam arcanorum disceret in in in praesente aurem secreto parietes aut praesente postridie penetrali in uxori conscii siquid vitae referente secreto ut aurem ideoque referente in acciderat aut secreto susurrasset interdum citerioris secreto ut ministro ideoque paterfamilias soli timebantur Amphiarao praesente interdum in disceret in penetrali inclitis secreto timebantur acciderat citerioris timebantur uxori Marcio vatibus praesente in etiam praesente soli Marcio Amphiarao siquid acciderat Amphiarao paterfamilias soli arcanorum aurem disceret ut imperator praesente disceret parietes vitae referente acciderat disceret praesente.',
        skill1:'https://i.imgur.com/cSxKCvH.png',
        skill2:'https://i.imgur.com/o72JK5Y.png',
        skill3:'https://i.imgur.com/2fpyO3l.png',
        skill4:'https://i.imgur.com/eMd0uGR.png',
        skill5:'https://i.imgur.com/zHVwYjR.png',
        skill6:'https://i.imgur.com/8jfpLnG.png',
    },
    {
        name:'Yukari',
        bp:'Slash / Thunder',
        infos:'Vitae soli penetrali conscii susurrasset Marcio aurem referente postridie nullo disceret secreto paterfamilias acciderat secreto secreto in susurrasset paterfamilias imperator etiam arcanorum disceret in in in praesente aurem secreto parietes aut praesente postridie penetrali in uxori conscii siquid vitae referente secreto ut aurem ideoque referente in acciderat aut secreto susurrasset interdum citerioris secreto ut ministro ideoque paterfamilias soli timebantur Amphiarao praesente interdum in disceret in penetrali inclitis secreto timebantur acciderat citerioris timebantur uxori Marcio vatibus praesente in etiam praesente soli Marcio Amphiarao siquid acciderat Amphiarao paterfamilias soli arcanorum aurem disceret ut imperator praesente disceret parietes vitae referente acciderat disceret praesente.',
        skill1:'https://i.imgur.com/9lMn26G.png',
        skill2:'https://i.imgur.com/7VczT00.png',
        skill3:'https://i.imgur.com/CT7YjPs.png',
        skill4:'https://i.imgur.com/TCv2UL2.png',
        skill5:'https://i.imgur.com/k9OVoS1.png',
        skill6:'https://i.imgur.com/o4qxVbT.png',
    },
    {
        name:'Carol',
        bp:'Pierce / Nature',
        infos:'tkBossInfos\ntkBossInfos',
        skill1:'https://i.imgur.com/Ftu3LgQ.png',
        skill2:'https://i.imgur.com/jEBLZ0c.png',
        skill3:'https://i.imgur.com/MzECGp5.png',
        skill4:'https://i.imgur.com/eN8k3nE.png',
        skill5:'https://i.imgur.com/AZxY4qR.png',
        skill6:'https://i.imgur.com/Db9CQFm.png',
    },
    {
        name:'Reeft & Natalie',
        bp:'Tout',
        infos:'tkBossInfos\ntkBossInfos',
        skill1:'https://i.imgur.com/y76LEw0.png',
        skill2:'https://i.imgur.com/tEWnb8a.png',
        skill3:'https://i.imgur.com/dH8TAlj.png',
        skill4:'https://i.imgur.com/kyNpZcQ.png',
        skill5:'https://i.imgur.com/VKBhhC9.png',
        skill6:'https://i.imgur.com/M1lRqwT.png',
    },
    {
        name:'Augustus',
        bp:'Holy / Dark',
        infos:'tkBossInfos\ntkBossInfos',
        skill1:'https://i.imgur.com/mxwMghx.png',
        skill2:'https://i.imgur.com/nbZ0J9R.png',
        skill3:'https://i.imgur.com/MopcW1q.png',
        skill4:'https://i.imgur.com/3wVT1K1.png',
        skill5:'https://i.imgur.com/X5sSivJ.png',
        skill6:'https://i.imgur.com/30Zi69w.png',
    }
]

export default tkContent;