const tkContent = [
    {
        name:'Faya',
        bp:'Strike / Dark',
        infos:"Le combat contre Faya est l'un des plus simple d'après moi. En tant que PNJ, il faut principalement maintenir sur les membres du groupes différents buffs.\n Pour ce faire, rien de plus simple, la prioritée est sur les sorts 2,3 et 5, qui appliquent les buffs aux membres se trouvant dans la zone du sort.\n Pour être encore plus utile, le PNJ peut aussi utiliser le 5ème sort pour ramener le boss sur lui et l'empêcher de se téléporter pendant 5 secondes, permettant au groupe d'infliger un maximum de dégâts pendant cette durée.",
        skill1:'https://i.imgur.com/cSxKCvH.png',
        skill2:'https://i.imgur.com/o72JK5Y.png',
        skill3:'https://i.imgur.com/2fpyO3l.png',
        skill4:'https://i.imgur.com/eMd0uGR.png',
        skill5:'https://i.imgur.com/zHVwYjR.png',
        skill6:'https://i.imgur.com/8jfpLnG.png',
    },
    {
        name:'Yukari',
        bp:'Slash / Thunder',
        infos:"Le combat contre Yukari peut être un peu plus compliqué pour certains (augmentez vos résistances les enfants). Cependant si vous êtes attentifs et évitez la confrontation directe avec ses invocations, vous devriez vous en sortir sans trop de problème.\n Concernant le PNJ, il est recommandé de spam le 2ème sort à partir de moment ou vous avez les sorts, ce sort permet de stacker un buff de précision sur les membres du groupe.\n Le 3ème sort est un sort qui pourrait vous faciliter la vie, surtout si vous manquez de résistances, il vous permettra de retirer d'un allié ciblé, ainsi que de réduire les dégâts physiques qu'il prendra.\n Le 4ème sort permettra à votre équipe un peu de répis si la situation devenait tendue.\n Le 6ème sort est le plus important dans le lot, il permettra de retirer au boss son immunité aux dégâts. Facile de la repérer, elle ne prendra plus de dégâts, se soignera, et aura l'apparence d'un arbre.",
        skill1:'https://i.imgur.com/9lMn26G.png',
        skill2:'https://i.imgur.com/7VczT00.png',
        skill3:'https://i.imgur.com/CT7YjPs.png',
        skill4:'https://i.imgur.com/TCv2UL2.png',
        skill5:'https://i.imgur.com/k9OVoS1.png',
        skill6:'https://i.imgur.com/o4qxVbT.png',
    },
    {
        name:'Carol',
        bp:'Pierce / Nature',
        infos:"Ce combat est simple comme bonjour, tout comme le rôle du PNJ ! Il s'agira ici d'empêcher le boss de se soigner.\n Carol invoquera des infirmières à plusieurs reprises. Il y a 3 types d'infirmières, celles qui envoient de la lumière vers elle pour la soigner, celles qui viennent à elle pour la soigner, et celles qui vous attaquent.\n Le 2ème sort empêchera la lumière de soigner le boss, le 3ème empêchera les infirmières au corp à corp de soigner le boss, et le 6ème vous permettra de forcer les infirmières à quitter le terrain si besoin.",
        skill1:'https://i.imgur.com/Ftu3LgQ.png',
        skill2:'https://i.imgur.com/jEBLZ0c.png',
        skill3:'https://i.imgur.com/MzECGp5.png',
        skill4:'https://i.imgur.com/eN8k3nE.png',
        skill5:'https://i.imgur.com/AZxY4qR.png',
        skill6:'https://i.imgur.com/Db9CQFm.png',
    },
    {
        name:'Reeft & Natalie',
        bp:'Tout',
        infos:"Il existe plusieurs approches possibles pour ce combat. Il est possible de run les deux boss en même temps, en s'assurant de ne jamais se faire toucher par l'un d'eux. Il est aussi possible de commencer par en attirer un, le tomber à plus ou moins 10% de ses HP, avant d'engager le combat avec le deuxième boss, le tuer et finir le premier.\n Quelque soit votre approche, notez que les bosses ne bougeront pas du milieu si vous ne les engagez pas avec un stun. Pour n'en attirer qu'un, il est recommendé d'utiliser le sleep de l'illu et de le laisser venir vers vous.\n Si vous attirez un boss pour le combattre de face, il est conseillé de commencer par Reeft, étant donné que si Nathalie vous touche, elle va d'abord stun le groupe régulièrement, mais aussi elle va téléporter Reeft sur elle, rendant le combat plus compliqué. Il est recommendé qu'un des joueurs run Reeft une fois qu'il est LOW HP, pour que les autres puissent combattre Natalie en utilisant, si possible, que des sorts mono cibles pour éviter de reprendre l'aggro de Reeft lorsqu'il sera téléporté. \n Ici le PNJ aura un très gros impact sur la vitesse à laquelle les boss vont mourir. Premièrement il aura son 1er et 2ème spells qui auront chacun un impact sur un boss. Le premier sera pour reeft, et le deuxieme pour Natalie.\n Le 3ème sort réduira les dégâts qu'inflige le boss, mais le plus important sera le 4ème sort, qui augmentera les dégâts reçus par le boss de 50% !",
        skill1:'https://i.imgur.com/y76LEw0.png',
        skill2:'https://i.imgur.com/tEWnb8a.png',
        skill3:'https://i.imgur.com/dH8TAlj.png',
        skill4:'https://i.imgur.com/kyNpZcQ.png',
        skill5:'https://i.imgur.com/VKBhhC9.png',
        skill6:'https://i.imgur.com/M1lRqwT.png',
    },
    {
        name:'Augustus',
        bp:'Holy / Dark',
        infos:'Ce boss tape fort ! Il vous faudra MINIMUM 30k hp pour survivre (non négociable). Il faut absolument run ce boss, il ne doit pas vous toucher, sinon il y a de grandes chances que votre groupe tombe par terre.\n Sur ce boss on ne demandera pas de miracles de la part du PNJ, le réussir à la perfection demande pas mal de pratique. Il faut utiliser les différents sort au timing exact (0.5s) pour donner la bonne immunité à votre groupe.\n Cependant le 6ème sort peut vous sauver en cas de pépin, il soignera votre groupe !',
        skill1:'https://i.imgur.com/mxwMghx.png',
        skill2:'https://i.imgur.com/nbZ0J9R.png',
        skill3:'https://i.imgur.com/MopcW1q.png',
        skill4:'https://i.imgur.com/3wVT1K1.png',
        skill5:'https://i.imgur.com/X5sSivJ.png',
        skill6:'https://i.imgur.com/30Zi69w.png',
    }
]

export default tkContent;