const wikiContent = [
    {
    name: "Temple Knight Trial",
    level: 80,
    location: "Aven",
    short: "Aven",
    player: 5,
    npc: "Tyrosen",
    img: "https://i.imgur.com/WWxfDNh.png",
    fr: "Karen peut sembler un peu compliquée et chiante, mais elle est juste chiante ! /n Plus sérieusement, ce n'est pas un boss compliqué, il suffit que chacun remplisse son rôle et tout se passera bien. /n Premièrement en tant que healer, il faut absoluement éviter les aoes sinon vous allez vous faire endormir ! Pensez à débuff le Berserker dès qu'il se fera endormir pour être sûr qu'il soit prêt en cas de besoin. Une fois fait, vous pouvez débuff le Darkness Blade pour qu'il continue de faire la BP. /n Ensuite en tant que Darkness Blade, il faut s'occuper de le BP, mais aussi surveiller les Rams que Karen va invoquer, il y en a 3 différents, parmis ceux la, il faut en surveiller 2 qui rendent Karen immunisée aux dégats magiques. Le Darkness Blade doit les aggro et les attirer sur Karen, de manière à les tuer et faire la BP en même temps. Le troisième Ram (celui avec l'aura violette) sera pris par un DPS physique et enmené sur Karen. /n Maintenant en tant que Berserker, il faut faire attention aux aoes de Karen. Il y en a 2 différentes, on peut les différencier grâce aux effets visuels présent pendant que Karen fait son aoe. L'aoe avec des effets violets est le sleep, vous pouvez l'ignorer car le healer va vous débuff. Par contre, l'aoe avec des effets verts ne doit absolument pas être ignorée ! Si elle vous touche, vous recevez un debuff qui permettra a Karen de se soigner à chaque fois que vous la tapez. Il faudra donc la fear pendant qu'elle fait cette aoe, de manière à l'empêcher de la faire. /n Maintenant en Blade Master, il faudra faire la même chose que le Berserker, mais uniquement quand Karen sera immunisée au fear et qu'elle fait une aoe avec des effets verts. Vous pouvez aussi ignorer l'aoe avec les effets violet, puisque vous pouvez vous débuff seul. /n Et enfin en tant qu'Executionner, il vous suffit de taper le boss et de faire confiance à vos coéquipiers !",
    en: "Karen may look like a difficult and annoying boss, but that's not how it is. She is annoying, but fairly easy. Depending on your class you will need to pay attention to different things. /n First as a healer, you have to pay attention to the debuffs, and make sure you are not in Karen's aoes. If you are hit, you may fall asleep. Make sure to debuff the Berserker as fast as you can, so that he can do his job without any issue, once it's done, you can debuf the Darkness Blade. /n Now as the Darkness Blade, you have to pay attention to the rams that Karen will summons (the BP too). There's will be 3 different, you have to attack them exept the magic one (with a dark purple aura). If you don't do your job, your teammates can't deal any damage to Karen, and you will be stuck there forever. /n Now as the Berserker, you have to pay attentions to Karen's aoes. There are 2 different, you can tell them apart by the effects while she cast. The aoe with purple effects is the sleep, you can ignore this one, as the healer will debuff you. But the aoe with green effects will give a debuff to the players hit, and they will heal her with every hit. Your job would be to fear her when she cast this aoe, this way everyone can keep attacking. /n Now as the Blade Master, your job will be similar to the Berserker's job, you will ignore the sleep aoe, as you can debuff yourself. And when fear immunity is up, and Karen's is casting the green aoe, you will have to stun her, preventing her from healing. /n And now as the Executioner, you just have to hit and trust your mates.",
  },
  {
    name: "Double Door",
    level: '70-80',
    location: "",
    short: "?",
    player: '',
    npc: "Double Door / Ma'kai",
    img: "https://i.imgur.com/kNgCM7C.png",
    fr: "Karen peut sembler un peu compliquée et chiante, mais elle est juste chiante ! /n Plus sérieusement, ce n'est pas un boss compliqué, il suffit que chacun remplisse son rôle et tout se passera bien. /n Premièrement en tant que healer, il faut absoluement éviter les aoes sinon vous allez vous faire endormir ! Pensez à débuff le Berserker dès qu'il se fera endormir pour être sûr qu'il soit prêt en cas de besoin. Une fois fait, vous pouvez débuff le Darkness Blade pour qu'il continue de faire la BP. /n Ensuite en tant que Darkness Blade, il faut s'occuper de le BP, mais aussi surveiller les Rams que Karen va invoquer, il y en a 3 différents, parmis ceux la, il faut en surveiller 2 qui rendent Karen immunisée aux dégats magiques. Le Darkness Blade doit les aggro et les attirer sur Karen, de manière à les tuer et faire la BP en même temps. Le troisième Ram (celui avec l'aura violette) sera pris par un DPS physique et enmené sur Karen. /n Maintenant en tant que Berserker, il faut faire attention aux aoes de Karen. Il y en a 2 différentes, on peut les différencier grâce aux effets visuels présent pendant que Karen fait son aoe. L'aoe avec des effets violets est le sleep, vous pouvez l'ignorer car le healer va vous débuff. Par contre, l'aoe avec des effets verts ne doit absolument pas être ignorée ! Si elle vous touche, vous recevez un debuff qui permettra a Karen de se soigner à chaque fois que vous la tapez. Il faudra donc la fear pendant qu'elle fait cette aoe, de manière à l'empêcher de la faire. /n Maintenant en Blade Master, il faudra faire la même chose que le Berserker, mais uniquement quand Karen sera immunisée au fear et qu'elle fait une aoe avec des effets verts. Vous pouvez aussi ignorer l'aoe avec les effets violet, puisque vous pouvez vous débuff seul. /n Et enfin en tant qu'Executionner, il vous suffit de taper le boss et de faire confiance à vos coéquipiers !",
    en: "Karen may look like a difficult and annoying boss, but that's not how it is. She is annoying, but fairly easy. Depending on your class you will need to pay attention to different things. /n First as a healer, you have to pay attention to the debuffs, and make sure you are not in Karen's aoes. If you are hit, you may fall asleep. Make sure to debuff the Berserker as fast as you can, so that he can do his job without any issue, once it's done, you can debuf the Darkness Blade. /n Now as the Darkness Blade, you have to pay attention to the rams that Karen will summons (the BP too). There's will be 3 different, you have to attack them exept the magic one (with a dark purple aura). If you don't do your job, your teammates can't deal any damage to Karen, and you will be stuck there forever. /n Now as the Berserker, you have to pay attentions to Karen's aoes. There are 2 different, you can tell them apart by the effects while she cast. The aoe with purple effects is the sleep, you can ignore this one, as the healer will debuff you. But the aoe with green effects will give a debuff to the players hit, and they will heal her with every hit. Your job would be to fear her when she cast this aoe, this way everyone can keep attacking. /n Now as the Blade Master, your job will be similar to the Berserker's job, you will ignore the sleep aoe, as you can debuff yourself. And when fear immunity is up, and Karen's is casting the green aoe, you will have to stun her, preventing her from healing. /n And now as the Executioner, you just have to hit and trust your mates.",
  },
];

export default wikiContent;